remote_theme: pmarsceill/just-the-docs

search_enabled: true

heading_anchors: true

color_scheme: dark

# Aux links for the upper right navigation
aux_links:
  "Docs":
    - "//gillchristian.github.io/remote-data-ts/"
  "API Reference":
    - "//gillchristian.github.io/remote-data-ts/modules/"
  'GitHub':
    - 'https://github.com/gillchristian/remote-data-ts'
